import _ from 'lodash';

export default function () {
    // 实体：采购订单商品信息
    let defaults = {
		"id": "",
		"tenantId": "hfy",
		"itemCode": "",
		"purchaseOrderNo": "",
		"serialNo": "",
		"specificationType": "",
		"goodsName": "",
		"goodsCode": "",
		"taxNo": "",
		"attachNo": "",
		"goodsCode_customs": "",
		"goodsName_customs": "",
		"customsGoodsModel": "",
		"quantity": "",
		"price": "",
		"currency": "",
		"amount": "",
		"unit": "",
		"sellerCurrency": "",
		"sellerPrice": "",
		"sellerQuantity": "",
		"sellerGoodsValue": "",
		"controlledGoods": "",
		"telecomLicence": "",
		"superviseMode": "",
		"exchangeRate": "",
		"extrasTaxRate": "",
		"extrasTariff": "",
		"extrasVat": "",
		"freightRate": "",
		"premiumRate": "",
		"extrasRate": "",
		"buyerExchangeRate": "",
		"buyerCurrency": "",
		"buyerPrice": "",
		"buyerGoodsValue": "",
		"buyerTaxType": "",
		"buyerTaxRate": "",
		"totalAmount": "",
		"netWeight": "",
		"grossWeight": "",
		"volume": "",
		"brand": "",
		"sourceArea": "",
		"receiveQuantity": "",
		"inStorageQuantity": "",
		"buyerMaterialCode": "",
		"buyerMaterialName": "",
		"materialModel": "",
		"taxRate": "",
		"superviseTerm": "",
		"producerProduct": "",
		"storehouse": "",
		"passNo": "",
		"threecItem": ""

      };

    _.assign(this, defaults);
}
