import _ from 'lodash';

export default function () {
    // 实体：销售订单
    let defaults = {
		"id": "",
		"tenantId": "hfy",
		"salesOrderCode": "",
		"company": "",
		"companyName": "",
		"pickWay": "",
		"transportEfficiency": "",
		"transportEfficiencyName": "",
		"customer": "",
		"customerName": "",
		"deliveryConditions": "",
		"serviceFeeBase": "",
		"shipmentFeeType": "",
		"originOrderType": "",
		"entrust": "",
		"entrustName": "",
		"busiType": "",
		"carrier": "",
		"carrierName": "",
		"deliveryTime": "",
		"companyAbb": "",
		"contacts": "",
		"contactsName": "",
		"address": "",
		"shipmentFee": "",
		"trusteeCode": "",
		"customsType": "",
		"shippingType": "",
		"receiptTime": "",
		"receivingCompany": "",
		"telePhone": "",
		"shippingRoute": "",
		"shippingRouteName": "",
		"busiDate": "",
		"storeNo": "",
		"remark": "",
		"receiptRemark": "",
		"salesman": "",
		"fax": "",
		"finalCustomer": "",
		"finalCustomerName": "",
		"batchNo": "",
		"inspectionMethod": "",
		"inspectionMan": "",
		"inspectionManName": "",
		"plateNo": "",
		"inspectionReceive": "",
		"inspectionCost": "",
		"inspectionRemark": "",
		"supplierOrder": false,
		"descriptionOne": "",
		"deliveryOrder": false,
		"descriptionTwo": "",
		"stockStatus": "",
		"stockTime": "",
		"stockMan": "",
		"stockManName": "",
		"totalCardQuantity": "",
		"totalBox": "",
		"printer": "",
		"printTime": "",
		"shippingMode": ""

      };

    _.assign(this, defaults);
}
