import _ from 'lodash';

export default function () {
    // 实体：委托付款单
    let defaults = {
		"id": "",
		"tenantId": "hfy",
		"billNo": "",
		"payBeyond": false,
		"booked": false,
		"payNature": "",
		"payOperation": "",
		"delegete": "",
		"trustee": "",
		"agent": "",
		"payType": "",
		"payMontyType": "",
		"serviceChargePayerType": "",
		"checkNumber": "",
		"payMoneyRMBexchangeRate": "",
		"serviceChargePayer": "",
		"receiptsBill": "",
		"financialReceiptsAudit": "",
		"receiptsAmount": "",
		"billState": "",
		"incidentalPayerType": "",
		"ownReceiveBank": "",
		"incidentalPayer": "",
		"expectedAmountReceipt": "",
		"plannedPayDate": "",
		"payForOthersAmount": "",
		"termBillFinishDate": "",
		"remark": "",
		"advancePaymentAmount": "",
		"shouldReceiveBill": false,
		"termBillDays": "",
		"receiverUserName": "",
		"innerDeduction": false,
		"country": "",
		"ttServiceCharge": "",
		"serviceChargeMoneyType": "",
		"wayOfServiceCharge": "",
		"payeeAccount": "",
		"fullAccountArrival": false,
		"city": "",
		"swiftCode": "",
		"accountBeenPaid": false,
		"bankNO": "",
		"receiveBank": "",
		"destination": "",
		"settlementMethod": "",
		"payeePhone": "",
		"payeeFax": "",
		"invoiceName": "",
		"invoiceAbbreviation": "",
		"receiveBankAddress": "",
		"postscript": "",
		"discount": false,
		"discountType": "",
		"auditor": "",
		"auditTime": ""

      };

    _.assign(this, defaults);
}
