import validate from "@/domain/common/validate.js";
export default [
	/* {
		isString: true,
		key: "checkingInfoCode",
		name: "核对信息编码",
		prop: "checkingInfoCode",
		type: "string",
	},
	{
		isString: true,
		key: "scheduleBaseCode",
		name: "关联上货计划基本信息",
		prop: "scheduleBaseCode",
		type: "string",
	}, */
	{
		checked: true,
		key: "cutOrder",
		name: "已截单",
		prop: "cutOrder",
		type: "checkbox",
	},
	{
		isString: true,
		key: "totalOrders",
		name: "总单数",
		prop: "totalOrders",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		type: true,
		isString: true,
		key: "totalWeight",
		name: "总重量",
		prop: "totalWeight",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		isString: true,
		key: "totalUnitName",
		name: "总重量单位",
		prop: "totalUnitName",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		type: true,
		isString: true,
		key: "totalNetWeight",
		name: "卡板总毛重",
		prop: "totalNetWeight",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		isString: true,
		key: "netUnitName",
		name: "毛重单位",
		prop: "netUnitName",
		type: "string",
	},
	{
		isString: true,
		key: "boxCount",
		name: "总箱数",
		prop: "boxCount",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		selectOption: [],
		select: true,
		selectKey: "checkResult",
		key: "cutOrderResult",
		name: "截单核对结果",
		prop: "cutOrderResult",
		type: "checkbox",
	},
	{
		date: true,
		key: "cutOrderTime",
		name: "截单核对时间",
		prop: "cutOrderTime",
		type: "date",
	},
	{
		isString: true,
		key: "cutOrderUser",
		name: "截单核对人",
		prop: "cutOrderUser",
		type: "string",
	},
	{
		isString: true,
		key: "cutDifference",
		name: "截单核对差异",
		prop: "cutDifference",
		type: "string",
	},
	{
		checked: true,
		key: "loadResult",
		name: "装车核对结果",
		prop: "loadResult",
		type: "checkbox",
	},
	{
		date: true,
		key: "loadTime",
		name: "装车核对时间",
		prop: "loadTime",
		type: "date",
	},
	{
		isString: true,
		key: "loadUser",
		name: "装车核对人",
		prop: "loadUser",
		type: "string",
	},
	{
		isString: true,
		key: "loadDifference",
		name: "装车核对差异",
		prop: "loadDifference",
		type: "string",
	}
]