import validate from "@/domain/common/validate.js";
const rules = validate.setRequired();
export default [
	
	{
		isString: true,
		key: "goodsNameSpec",
		name: "货物名称及规格",
		prop: "goodsNameSpec",
		type: "string",
	},
	{
		isString: true,
		key: "packaging1",
		name: "包装方式及数量1",
		prop: "packaging1",
		type: "string",
	},
	{
		isString: true,
		key: "packaging2",
		name: "包装方式及数量2",
		prop: "packaging2",
		type: "string",
	},
	{
		isString: true,
		key: "payerAddress",
		name: "付货人名称及地址",
		prop: "payerAddress",
		type: "string",
	},
	{
		isString: true,
		key: "otherPayerAddress",
		name: "其他付货人名称及地址",
		prop: "otherPayerAddress",
		type: "string",
	},
	{
		isString: true,
		key: "consigneeAddress",
		name: "收货人名称及地址",
		prop: "consigneeAddress",
		type: "string",
	},
	{
		isString: true,
		key: "otherConsigneeAddress",
		name: "其他收货人名称及地址",
		prop: "otherConsigneeAddress",
		type: "string",
	},
	{
		isString: true,
		key: "licenseCode",
		name: "进/出口许可证编码",
		prop: "licenseCode",
		type: "string",
	},
	{
		isString: true,
		key: "shippingCode",
		name: "提单/空运托运单号编码",
		prop: "shippingCode",
		type: "string",
	},
	{
		isString: true,
		key: "plateNoHK",
		name: "香港车牌",
		prop: "plateNoHK",
		type: "string",
	},
	{
		isString: true,
		key: "driver",
		name: "司机",
		prop: "driver",
		type: "string",
	},
	{
		isString: true,
		key: "phoneNo",
		name: "大陆电话",
		prop: "phoneNo",
		type: "string",
	},
	{
		isString: true,
		key: "phoneNoHK",
		name: "香港电话",
		prop: "phoneNoHK",
		type: "string",
	},
	{
		isString: true,
		key: "carrierAddress",
		name: "承运商的地址",
		prop: "carrierAddress",
		type: "string",
	},
	{
		btn: true,
		key: "regulateType",
		name: "监管方式",
		prop: "regulateType",
		isShowPopover: true,
		readonly: true,
		required: true,
		type: "string",
		api: "getSupervisionModeList",
	},
	{
		isString: true,
		key: "carCustomsCode",
		name: "车辆海关编码",
		prop: "carCustomsCode",
		type: "string",
	},
	{
		type: true,
		isString: true,
		key: "netWeight",
		name: "重量/净重",
		prop: "netWeight",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		isString: true,
		key: "plateNo",
		name: "内地车牌",
		prop: "plateNo",
		type: "string",
	},
	{
		isString: true,
		key: "boxIdentification",
		name: "重箱或者空箱标识",
		prop: "boxIdentification",
		type: "string",
	},
	{
		type: true,
		isString: true,
		key: "trailerWeight",
		name: "托架/拖挂车自重",
		prop: "trailerWeight",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	},
	{
		type: true,
		isString: true,
		key: "grossWeight",
		name: "含车毛重",
		prop: "grossWeight",
		type: "number",
		rules: [{validator: validate.validateNum,}],
	}
]