import validate from "@/domain/common/validate"
const rules = validate.setRequired();
export default [
	{ title: "", showline:false, list: [
		{
			key: "billNo",
			name: "深圳收货入库单编号",
			prop: "billNo",
			type: "string",
			disabled: true,
		},
		{
			key: "delegeteBillNo",
			name: "委托单号",
			prop: "delegeteBillNo",
			type: "string",
			disabled: true,
		},
		{
			key: "inventoryCode",
			name: "存货编码",
			prop: "inventoryCode",
			type: "string",
			btn:true,
			rules: [{ required: true, message: '必填', trigger: 'blur' }]
		},
		{
			key: "inventoryName",
			name: "存货名称",
			prop: "inventoryName",
			type: "string",
			rules: [{ required: true, message: '必填', trigger: 'blur' }]
		},
		{
			key: "specificationType",
			name: "规格型号",
			prop: "specificationType",
			type: "string",
			rules: [{ required: true, message: '必填', trigger: 'blur' }]
		},
		// {
		// 	key: "tradeName",
		// 	name: "商品名称",
		// 	prop: "tradeName",
		// 	type: "string",
		// 	rules: [{ required: true, message: '必填', trigger: 'blur' }]
		// },
		{
			key: "brandName",
			name: "品牌",
			prop: "brandName",
			type: "string",
			btn: true,
			rules
		},
		{
			key: "originPlaceName",
			name: "产地",
			prop: "originPlaceName",
			type: "string",
			btn: true,
			rules
		},
		{
			key: "taxNo",
			name: "税号",
			prop: "taxNo",
			type: "string",
			btn: true
		},
		{
			key: "attachNo",
			name: "附号",
			prop: "attachNo",
			type: "string",
		},
		{
			key: "parameter",
			name: "参数",
			prop: "parameter",
			type: "string",
		},
		{
			key: "planTurn",
			name: "计划车序",
			prop: "planTurn",
			type: "string",
		},
		{
			key: "batchNo",
			name: "批次",
			prop: "batchNo",
			type: "string",
		},
		{
			key: "supplierBatchNo",
			name: "供应商批次号",
			prop: "supplierBatchNo",
			type: "string",
		},
	] },
	{ title: "", showline:true, list: [
		{
			key: "receiveQuantity",
			name: "应收数量",
			prop: "receiveQuantity",
			type: "string",
			rules
		},
		{
			key: "harvestQuantity",
			name: "实收数量",
			prop: "harvestQuantity",
			type: "string",
			rules
		},
		{
			key: "unitName",
			name: "计量单位",
			prop: "unitName",
			type: "string",
			btn: true,
			rules
		},
		{
			key: "quantity",
			name: "入库数量",
			prop: "quantity",
			type: "number",
			rules: [{ required: true, message: '必填', trigger: 'blur',validator: validate.validateNum }]
		},
		{
			key: "assistUnitName",
			name: "辅助计量单位",
			prop: "assistUnit",
			type: "string",
			btn: true
		},
		{
			key: "assictCount",
			name: "辅助数量",
			prop: "assictCount",
			type: "number",
			rules: [{validator: validate.validateNum,}],
		},
		{
			key: "shippingMarks",
			name: "唛头",
			prop: "shippingMarks",
			type: "string",
			rules
		},
		{
			key: "boxNoStart",
			name: "起始箱号",
			prop: "boxNoStart",
			type: "number",
			rules: [{ required: true, message: '必填', trigger: 'blur',validator: validate.validateNum }]
		},
		{
			key: "boxNoEnd",
			name: "结束箱号",
			prop: "boxNoEnd",
			type: "number",
			rules: [{ required: true, message: '必填', trigger: 'blur',validator: validate.validateNum }]
		},
		// {
		// 	key: "boxPlusNo",
		// 	name: "箱附号",
		// 	prop: "boxPlusNo",
		// 	type: "string",
		// },
		{
			key: "boxCount",
			name: "箱数",
			prop: "boxCount",
			type: "number",
			rules: [{ required: true, message: '必填', trigger: 'blur',validator: validate.validateNum }]
		},
		{
			key: "netWeight",
			name: "净重",
			prop: "netWeight",
			type: "number",
			rules: [{required: true, message: '必填', trigger: 'blur',validator: validate.validateNum,}],
		},
		{
			key: "grossWeight",
			name: "毛重",
			prop: "grossWeight",
			type: "number",
			rules: [{required: true, message: '必填', trigger: 'blur',validator: validate.validateNum,}],
		},
		{
			key: "volume",
			name: "体积",
			prop: "volume",
			type: "number",
			rules: [{validator: validate.validateNum,}],
		},
		{
			btn: true,
			readonly: true,
			key: "warehouseName",
			name: "仓库",
			prop: "warehouseName",
			type: "string",
			rules: [{ required: true, message: '必填', trigger: 'blur' }]
		},
		{
			btn: true,
			readonly: true,
			key: "storekeeperName",
			name: "仓管员",
			prop: "storekeeperName",
			type: "string",
			rules: [{ required: true, message: '必填', trigger: 'blur' }]
		},
		{
			key: "storehouse",
			name: "库位",
			prop: "storehouse",
			type: "string",
		},
		// {
		// 	text: true,
		// 	key: "contractNo",
		// 	name: "合同号",
		// 	prop: "contractNo",
		// 	type: "string",
		// 	rules
		// },
		// {
		// 	text: true,
		// 	key: "deliveryAddress",
		// 	name: "送货地址",
		// 	prop: "deliveryAddress",
		// 	type: "string",
		// 	rules
		// },
	] },
	// { title: "", showline:true, list: [	
	// 	{
	// 		key: "customer",
	// 		name: "客户",
	// 		prop: "customer",
	// 		type: "string",
	// 	},
	// 	{
	// 		key: "unitStandardCost",
	// 		name: "单位标准成本",
	// 		prop: "unitStandardCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "standardCost",
	// 		name: "标准成本",
	// 		prop: "standardCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "unitPurchaseCost",
	// 		name: "单位采购成本",
	// 		prop: "unitPurchaseCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "purchaseCost",
	// 		name: "采购成本",
	// 		prop: "purchaseCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "unitActualCost",
	// 		name: "单位实际成本",
	// 		prop: "unitActualCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "actualCost",
	// 		name: "实际成本",
	// 		prop: "actualCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "shareCost",
	// 		name: "累计分摊费用",
	// 		prop: "shareCost",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "price",
	// 		name: "单价",
	// 		prop: "price",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "taxRate",
	// 		name: "税率",
	// 		prop: "taxRate",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "priceContainTax",
	// 		name: "含税单价",
	// 		prop: "priceContainTax",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "priceNet",
	// 		name: "实际单价",
	// 		prop: "priceNet",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "actualTaxPrice",
	// 		name: "实际含税单价",
	// 		prop: "ActualTaxPrice",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "amount",
	// 		name: "金额",
	// 		prop: "amount",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "tax",
	// 		name: "税额",
	// 		prop: "tax",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "taxCurrency",
	// 		name: "税额本位币",
	// 		prop: "taxCurrency",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "priceTax",
	// 		name: "价税合计",
	// 		prop: "priceTax",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "priceTaxCurrency",
	// 		name: "价税合计本位币",
	// 		prop: "priceTaxCurrency",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		checked: true,
	// 		key: "completeCancellation",
	// 		name: "完全核销",
	// 		prop: "completeCancellation",
	// 		type: "checkbox",
	// 	},
	// 	{
	// 		key: "cancelledQuantity",
	// 		name: "已核销数量",
	// 		prop: "cancelledQuantity",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "cancelledAmount",
	// 		name: "已核销金额",
	// 		prop: "cancelledAmount",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "writeOffQuantity",
	// 		name: "累计冲销数量",
	// 		prop: "writeOffQuantity",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "returnedQuantity",
	// 		name: "退货数量",
	// 		prop: "returnedQuantity",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		selectOption: [],
	// 		selectKey: "verifyBillType",
	// 		key: "keyBillType",
	// 		name: "核心单据类型",
	// 		prop: "keyBillType",
	// 		type: "select",
	// 	},
	// 	{
	// 		key: "keyAmount",
	// 		name: "核心金额",
	// 		prop: "keyAmount",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "keyQuantity",
	// 		name: "核心数量",
	// 		prop: "keyQuantity",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "purchaseOrg",
	// 		name: "采购组织",
	// 		prop: "purchaseOrg",
	// 		type: "string",
	// 	},
	// 	{
	// 		key: "settlementSupplier",
	// 		name: "结算供应商",
	// 		prop: "settlementSupplier",
	// 		type: "string",
	// 	},
	// 	{
	// 		key: "remark",
	// 		name: "备注",
	// 		prop: "remark",
	// 		type: "string",
	// 	},
	// 	{
	// 		key: "customsValue",
	// 		name: "报关货值",
	// 		prop: "customsValue",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		selectOption: [],
	// 		selectKey: "currencyName",
	// 		key: "customsValueCurrency",
	// 		name: "报关货值币别",
	// 		prop: "customsValueCurrency",
	// 		type: "select",
	// 	},
	// ] },
	// { title: "", showline:true, list: [
	// 	{
	// 		key: "incomeInvoiceNo",
	// 		name: "来货发票号",
	// 		prop: "incomeInvoiceNo",
	// 		type: "string",
	// 	},
	// 	{
	// 		key: "commissionPriceOne",
	// 		name: "佣金单价1",
	// 		prop: "commissionPriceOne",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "commissionPriceTwo",
	// 		name: "佣金单价2",
	// 		prop: "commissionPriceTwo",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "commissionOne",
	// 		name: "佣金1",
	// 		prop: "commissionOne",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "commissionTwo",
	// 		name: "佣金2",
	// 		prop: "commissionTwo",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "exchangeRate",
	// 		name: "入库汇率",
	// 		prop: "exchangeRate",
	// 		type: "number",
	// 		// rules: [{validator: validate.validateNum,}],
	// 	},
	// 	{
	// 		key: "commissionUserOne",
	// 		name: "佣金人1",
	// 		prop: "commissionUserOne",
	// 		type: "string",
	// 	},
	// 	{
	// 		key: "commissionUserTwo",
	// 		name: "佣金人2",
	// 		prop: "commissionUserTwo",
	// 		type: "string",
	// 	},
	// 	{
	// 		selectOption: [],
	// 		selectKey: 'billStatus',
	// 		key: "billType",
	// 		name: "单据类型",
	// 		prop: "billType",
	// 		type: "select",
	// 	},
	// 	{
	// 		key: "supplier",
	// 		name: "供应商",
	// 		prop: "supplier",
	// 		type: "string",
	// 	}
	// ] },
]