import _ from 'lodash';

export default function () {
  // 实体：买方接提货
  let defaults = {
    "id": "",
    "tenantId": "hfy",
    "itemCode": "",
    "billNo": "",
    "carrierCode": "",
    "carrierName": "",
    "hasAssignCarrier": false,
    "pickUpGoods": "",
    "delegeteBillNo": "",
    "dispatchOrganizationCode": "",
    "dispatchOrganizationName": "",
    "sendCity": "",
    "sendCityName": "",
    "receiptCity": "",
    "receiptCityName": "",
    "timeLimit": "",
    "timeLimitName": "",
    "deliverDate": "",
    "transportMode": "",
    "arrivalDate": "",
    "receiveCompanyCode": "",
    "receiveCompanyName": "",
    "receiveContactId": "",
    "receiveContactName": "",
    "entrustReceive": false,
    "receivePayment": false,
    "waitNotice": false,
    "dispatchLine": "",
    "dispatchLineName": "",
    "contactTel": "",
    "goodsPacking": "",
    "area": "",
    "areaName": "",
    "phone": "",
    "receivePostCode": "",
    "receiveAddress": "",
    "paymentMode": "",
    "premium": "",
    "currency": "",
    "invoiceWithGoods": false,
    "needCollectFee": false,
    "goodsValueContainFee": false,
    "invoiceNo": "",
    "urgent": false,
    "costPriority": false,
    "timeLimitPriority": false,
    "deliveryPriority": false,
    "underPartyType": "",
    "underParty": "",
    "underPartyName": "",
    "premiumPartyType": "",
    "premiumParty": "",
    "premiumPartyName": "",
    "collectFeeType": "",
    "cashAmount": "",
    "collectCurrency": "",
    "deliveryMode": "",
    "sendMode": "",
    "costRange": "",
    "chequeAmount": "",
    "grossWeight": "",
    "netWeight": "",
    "pieces": "",
    "chargeObject": "",
    "inland": false,
    "pickUpAddress": "",
    "remark": "",
    "deliverRemark": "",
    status: null

  };

  _.assign(this, defaults);
}
