import _ from 'lodash';

export default function () {
    // 实体：委托方
    let defaults = {
		"id": "",
		"tenantId": "hfy",
		"clientNo": "",
		"clientName": "",
		"consociationStatus": "",
		"clientLevel": "",
		"customsCredit": "",
		"billStatus": "",
		"aboveAccountPeriod": false,
		"aboveAmount": false,
		"allowOrder": false,
		"inBlacklt": false,
		"suspiciousCustomer": false,
		"clientShortName": "",
		"clientEnName": "",
		"socialCreditCode": "",
		"shortCode": "",
		"parentCode": "",
		"parentName": "",
		"inlandDestination": "",
		"registeredNo": "",
		"irsNumber": "",
		"landTaxNumber": "",
		"legalPerson": "",
		"clientNature": "",
		"tel": "",
		"email": "",
		"url": "",
		"importantMonitor": false,
		"importantFocus": false,
		"fax": "",
		"orderReceiverName": "",
		"orderReceiverCode": "",
		"orderFollowerName": "",
		"orderFollowerCode": "",
		"customerTradeCode": "",
		"clientTradeName": "",
		"orderTime": "",
		"businessLicenseAddress": "",
		"crCode": "",
		"effectiveDate": "",
		"failureDate": "",
		"remark": "",
		"organizationNo": "",
		"registerMoney": "",
		"registerCurrency": "",
		"specialRemark": "",
		"establishedTime": "",
		"accountPeriod": "",
		"customerLimit": "",
		"minCharge": "",
		"authEmail": "",
		"keyWordRemark": "",
		"customsRating": "",
		"outcomeOwner": "",
		"outcome": "",
		"systemUser": false,
		"enableDate": "",
		"disableDate": "",
		"noExportLimit": "",
		"exportTaxLimit": "",
		"exportMatLimit": "",
		"businessLicense": "",
		"orderNum": "",
		"totalAmount": "",
		"avgAgencyFee": "",
		"ranked": "",
		"businessScope": "",
		"parity": "",
		"country": "",
		"province": "",
		"city": "",
		"county": "",
		"area": ""
		
      };

    _.assign(this, defaults);
}
